# Generated by Django 5.0.4 on 2024-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="links", to="collection.collection"
            ),
        ),
    ]
